### PR TITLE
Automatically restart streamdeck at wake-up.

### PR DESCRIPTION
**Pull request by oxhak**
replace YOUR_USERNAME with your linux user name
place this script in /usr/lib/systemd/system-sleep/
make it executable with chmod+x restart_streamdeck_wakeup.sh
systemd automatically execute it at wake-up

### CODE REVIEW

**Comment by oparada1988** [comment]
This didnt work for me, Ubuntu 20.04.4 LTS

**Comment by sftim** [comment]
I'm not sure this is the right fix, to be honest. It hard-codes a bunch of assumptions (eg use of X11 as a display server; display is `:0`; Stream Deck tool is `/usr/bin/streamdeck`.

**Comment by oxhak** [comment]
> I'm not sure this is the right fix, to be honest. It hard-codes a bunch of assumptions (eg use of X11 as a display server; display is `:0`; Stream Deck tool is `/usr/bin/streamdeck`.

You are right, it works under Archlinux and it should be adapted to everyone. The goal is to kill the process and restart it after the computer wakes up.

**Comment by dodgyrabbit** [comment]
FYI a proper fix is underway to recover after suspend/resume

**Comment by dodgyrabbit** [comment]
A fix was pushed some time back that will allow it to detect and recover from a suspend. There is also a systemd fix that will allow systemd to stop/start it. Closing this PR.

**Pull request closed without merging**
