### PR TITLE
Basic window and tray cleanup

### PR DESCRIPTION
**Pull request by PeterShinners**
Several small fixes and quality of life improvements for the tray icon and window

- Tray context menu not interrupted by window activation
- Keys widget becomes combobox with examples and named keys builtin
- Added help menu with links to websites
- About dialog shows application version and primary dependency versions

### CODE REVIEW

**Comment by flexiondotorg** [comment]
Thanks for this, I merged this PR into a local build. Works great.

**Comment by flexiondotorg** [comment]
Thanks for working on this. I merged this pull request into a local build and it works great.

**Comment by flexiondotorg** [comment]
@dodgyrabbit I think this can be merged.

**Comment by dodgyrabbit** [comment]
Thank you @PeterShinners for your contribution. I've merged this in.

**Pull request merged**
