### PR TITLE
Add support for Font configuration (font and font size)

### PR DESCRIPTION
**Pull request by rkmax**
A couple of weeks ago I brought a StreamDeck MK.2  and thanks to this project I was able to migrate from my old macro pad quickly. 

## Description of changes

Add the feature of changing the font and font size of the button's text.

Hopefully, this MR follows the conventions of your project, let me know if something else is missing to move forward with this MR

## Preview Before
image

## Preview After
image

### CODE REVIEW

**Comment by 4s3ti** [comment]
HI, seems the main project as reached a stale state as the project owner seems to have disappeared, and we are trying to keep it alive. 

you are welcome to participate in the discussion here: https://github.com/timothycrosley/streamdeck-ui/issues/357 so we can actually decide  a path forward and hopefully accept your contribution into it.

**Comment by rkmax** [comment]
> 



> HI, seems the main project as reached a stale state as the project owner seems to have disappeared, and we are trying to keep it alive.
> 
> you are welcome to participate in the discussion here: #357 so we can actually decide a path forward and hopefully accept your contribution into it.

Awesome!

**Comment by 4s3ti** [comment]
@rkmax  feel free to move this PR to: https://github.com/streamdeck-linux-gui/streamdeck-linux-gui 

please be sure to read the new contribution guide specially in regard to git commits.

**Comment by rkmax** [comment]
> @rkmax feel free to move this PR to: https://github.com/streamdeck-linux-gui/streamdeck-linux-gui
> 
> please be sure to read the new contribution guide specially in regard to git commits.

understood!

**Pull request closed without merging**
