### PR TITLE
Fix Test GitHub Action

### PR DESCRIPTION
**Pull request by tylerjw**
Fixes https://github.com/timothycrosley/streamdeck-ui/issues/104

This is an attempt to fix the various CI errors.

### CODE REVIEW

**Comment by tylerjw** [comment]
I don't understand why the `test.yml` action didn't run.  Do you know why it isn't running?

**Comment by tylerjw** [comment]
Closing and re-opening to see if I can trigger the test workflow.  (discovered it was manually disabled through github ui, enabled it to try to test this).

**Comment by tylerjw** [comment]
Try again, this time using https://github.com/marketplace/actions/gabrielbb-xvfb-action

**Comment by tylerjw** [comment]
Ok, I think this is good.  I'm not sure what to do about the travis error on MacOS.  I added a poetry cache to the github action as that seems to speed up the `poetry install`.

The issue with travis seems to be that the project requires a minimum of python 3.8 and that's not available on the MacOS runner version used by the travis run.  Maybe there is a newer version of the runner we could use, or maybe we could use python 3.7?

**Comment by dodgyrabbit** [comment]
> discovered it was manually disabled through github ui

Yes, figured we won't want to use up unecessary Github Action minutes if it's known to be failing.

>  I added a poetry cache to the github action as that seems to speed up the poetry install.

Great, thanks.

> I'm not sure what to do about the travis error on MacOS

I had to figure out a bunch of things here by myself, so some of this info may be incorrect:
* This project uses some kind of cookie-cutter templating system, probably because @timothycrosley has a lot of different projects to maintain.
* There is a tool called "cruft" that updates a project, based on main template. Presumably, the goal is to update the main template and then all his smaller projects update themselves based on the newer template. I could not readily find the source code for cruft.
* When this project was originally created, Travis was the CI tool of choice.
* Github has subsequently released github actions, which has a free tier and makes CI possible without Travis
* When I reviewed what this cruft thingy does, I saw it pulls against https://github.com/timothycrosley/cookiecutter-python.
* That template now uses github actions. 

So ultimately I *think* we can completely deprecate Travis and just let this github action do it's thing. There may be some more nuanced things - like better support for headless, OSX and so forth. However, for now my thinking is focus on the Linux community anyways, since you can use the Elgato version on OSX and Windows (even though this could all work there too).

**Pull request merged**
